# POST http://localhost:8080/api/orders
# Accept: application/json
# Content-Type: application/json

# {
#   "item": "Grocery",
#   "quantity": 2,
#   "price": 100,
#   "status": "Pending",
#   "createdAt": "2025-11-02T21:50:00"
# }

# ###

# POST http://localhost:8080/api/orders?discount=10
# Accept: application/json
# Content-Type: application/json

# {
#   "item": "Computer Display",
#   "quantity": 2,
#   "price": 100,
#   "status": "Pending",
#   "createdAt": "2025-11-02T21:50:00"
# }

# ###

# GET http://localhost:8080/api/orders
# Accept: application/json
# ###

# GET http://localhost:8080/api/orders/search?itemName=computer
# Accept: application/json


# ###

# POST http://localhost:8080/api/orders
# Accept: application/json
# Content-Type: application/json

# {
#     "id": 3,
#     "item": "Computer Monitor",
#     "quantity": 2,
#     "price": 1200.5,
#     "status": "Returned",
#     "createdAt": "2025-11-02T21:50:00"
#   }

  ###

GET http://localhost:8080/api/users/1
Accept: application/json


###
# GET http://localhost:8080/api/users/web/100
# Accept: application/json


###

# GET http://localhost:8080/api/orders
# Accept: application/json

###




